document.querySelector('#Title1').addEventListener('click',function(){
    document.querySelector('#Content1').style.display='block';
})
document.querySelector('#Title2').addEventListener('click',function(){
    document.querySelector('#Content2').style.display='block';
})
document.querySelector('#Title3').addEventListener('click',function(){
    document.querySelector('#Content3').style.display='block';
})
document.querySelector('#Title4').addEventListener('click',function(){
    document.querySelector('#Content4').style.display='block';
})
document.querySelector('#Title5').addEventListener('click',function(){
    document.querySelector('#Content5').style.display='block';
})